name: Auto Merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  contributors:
    runs-on: ubuntu-latest
    if: github.actor == 'hanspagel'
    steps:
      - name: Approve PR
        if: contains(github.event.pull_request.title, 'docs(contributor)')
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Enable auto-merge
        if: contains(github.event.pull_request.title, 'docs(contributor)')
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
